name: Docs

on:
  push:
    branches: [ "viur" ]
  pull_request:
    branches: [ "viur" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci --include=optional
          cd packages/webawesome && npm run build
      - name: collect
        run: |
            mkdir -p combined_site
            cp -r packages/webawesome/_site/* combined_site/
            cp -r packages/webawesome/dist-cdn/* combined_site/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
