name: Docs

on:
  push:
    branches: [ "viur" ]
  pull_request:
    branches: [ "viur" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          cd packages/webawesome && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/webawesome/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
